name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 333
        script: |
            cd /var/www/html/antareja
            export COMPOSER_ALLOW_SUPERUSER=1; composer show;
            git pull
            git status
            npm install
            npm run build
            composer update
            git pull
            php artisan migrate:status
