name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 333
        script: |
            # Masuk ke direktori website
            echo "========= Masuk ke direktori website ========="
            cd /var/www/html/antareja
            echo -e "\n\n"

            # Mengubah isi .env untuk APP_ENV
            echo "========= Mengubah isi .env untuk APP_ENV ========="
            sed -i 's/APP_ENV=.*/APP_ENV=production/g' .env
            echo -e "\n\n"

            # Mengubah isi .env untuk APP_DEBUG
            echo "========= Mengubah isi .env untuk APP_DEBUG ========="
            sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/g' .env
            echo -e "\n\n"

            echo "========= Mengubah isi .env untuk DB_HOST ========="
            sed -i 's/DB_HOST=.*/DB_HOST=157.245.199.47/g' .env
            echo -e "\n\n"

            # Mengubah isi .env untuk DB_PORT
            echo "========= Mengubah isi .env untuk DB_PORT ========="
            sed -i 's/DB_PORT=.*/DB_PORT=3306/g' .env
            echo -e "\n\n"

            # Mengubah isi .env untuk DB_DATABASE
            echo "========= Mengubah isi .env untuk DB_DATABASE ========="
            sed -i 's/DB_DATABASE=.*/DB_DATABASE=antareja/g' .env
            echo -e "\n\n"

            # Mengubah isi .env untuk DB_USERNAME
            echo "========= Mengubah isi .env untuk DB_USERNAME ========="
            sed -i 's/DB_USERNAME=.*/DB_USERNAME=antarejadbpublic/g' .env
            echo -e "\n\n"

            # Mengubah isi .env untuk DB_PASSWORD
            echo "========= Mengubah isi .env untuk DB_PASSWORD ========="
            sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=antarejadb2023/g' .env
            echo -e "\n\n"

            # Masuk ke direktori public
            echo "========= Masuk ke direktori public ========="
            cd /var/www/html/antareja/public
            echo -e "\n\n"

            # Menghapus folder build
            echo "========= menghapus folder build ========="
            rm -r build/
            echo -e "\n\n"

            # Masuk ke direktori website
            echo "========= Masuk ke direktori website ========="
            cd /var/www/html/antareja
            echo -e "\n\n"

            # Menjalankan COMPOSER ALLOW SUPERUSER
            echo "========= Menjalankan COMPOSER ALLOW SUPERUSER ========="
            export COMPOSER_ALLOW_SUPERUSER=1; composer show;
            echo -e "\n\n"

            # Menjalankan git pull
            echo "========= Menjalankan git pull ========="
            git pull
            echo -e "\n\n"

            # Menjalankan git status
            echo "========= Menjalankan git status ========="
            git status
            echo -e "\n\n"

            # Menjalankan npm install
            echo "========= Menjalankan npm install ========="
            npm install
            echo -e "\n\n"

            # Menjalankan npm run build
            echo "========= Menjalankan npm run build ========="
            npm run build
            echo -e "\n\n"

            # Menjalankan composer uodate
            echo "========= Menjalankan composer update ========="
            composer update
            echo -e "\n\n"

            # Menjalankan git pull
            echo "========= Menjalankan git pull ========="
            git pull
            echo -e "\n\n"

            # Menjalankan php artisan migrate
            echo "========= Menjalankan php artisan migrate ========="
            php artisan migrate:fresh --seed

            # Menjalankan maintenance mode
            echo "========= Menjalankan maintenance mode ========="
            php artisan down --secret="9909517125065786"
